import './globals.css'

export const metadata = {
  title: 'Chat with me:)',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='fixed bg-blue-950 overflow-hidden'>
        {children}
      </body>
    </html>
  )
}
